# Copyright 2023 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""add_created_time_to_function

Revision ID: 89ac3146d0ed
Revises: 28383af526f3
Create Date: 2023-05-23 11:14:02.839980

"""
import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import mlrun.api.utils.db.sql_collation

# revision identifiers, used by Alembic.
revision = '89ac3146d0ed'
down_revision = '28383af526f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runs",
        sa.Column(
            "created",
            sa.TIMESTAMP(),
            default=datetime.datetime.utcnow,
        ),
    )
    connection = op.get_bind()
    connection.execute("UPDATE my_table SET created = updated")

    op.add_column(
        "runs",
        sa.Column(
            "created_by",
            sa.String(length=255, collation="utf8_bin"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "created")
    # ### end Alembic commands ###

