"""add_created_time_to_function

Revision ID: 89ac3146d0ed
Revises: 28383af526f3
Create Date: 2023-05-23 11:14:02.839980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import mlrun.api.utils.db.sql_collation

# revision identifiers, used by Alembic.
revision = '89ac3146d0ed'
down_revision = '28383af526f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runs",
        sa.Column(
            "name",
            sa.String(
                length=255,
                collation=mlrun.api.utils.db.sql_collation.SQLCollationUtil.collation(),
            ),
            default="no-name",
        ),
    )
    op.add_column(
        "runs", sa.Column("updated", sa.TIMESTAMP(), default=datetime.datetime.utcnow)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "updated")
    op.drop_column("runs", "name")
    # ### end Alembic commands ###
